### ISSUE TITLE
关于扇形技能指示器

### ISSUE THREAD

**Issue by Meta404Dev** [AllenKashiwa/StudyUnity#1]
这样的效果并不能随地形而改变吧，能不能让shader附着在地形上

**Comment by AllenKashiwa** [comment]
你好，http://baizihan.me/2016/10/draw-sector/  我在这篇文章有讲到，想要附着在地形上，需要用绘制面片的方式。计算点的位置与高度，以及纹理UV，可以实现你想要的效果。这种方式有机会我也可以写篇文章。但网络上应该已经有对应的了，你可以找找看。

**Comment by Meta404Dev** [comment]
可能是我搜索的方式不对吧，网上根本没有找到相关的资料，能否麻烦提供以下相关资料链接呢，万分感谢！

**Comment by AllenKashiwa** [comment]
可以看看这篇文章：http://blog.csdn.net/lyh916/article/details/50383376 
他的绘制实心扇形部分就是你想要的。他在圆心到边的方向上相当于只分了一段，点都集中在圆心和边上。你要有高度变化的话需要改一下，分多段，就是圆心到边上有多次细分，算出每个点的位置，组成多个三角形。
